
# plugins: 
#     - {name: static_map,       type: "costmap_2d::StaticLayer"}
#     - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
plugins: []
global_costmap:
  global_frame: camera_odom_frame
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  rolling_window: true
  # “global_frame”参数定义了代价地图运行所在的坐标帧。
  # 在这种情况下,我们会选择/map坐标帧。 
  # “robot_base_frame”参数定义了代价地图参考的的机器底盘的坐标帧。
  # “update_frequency”参数决定了代价地图更新的频率。 
  # “static_map”参数决定代价地图是否根据map_server提供的地图初始化。
  # 如果你不使用现有的地图，设为false。