# plugins: 
#     - {name: static_map,       type: "costmap_2d::StaticLayer"}
#     - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
plugins: []
local_costmap:
  global_frame: camera_odom_frame
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05
  # “global_frame”，“robot_base_frame”，“update_frequency”，“static_map”参数与全局配置意义相同。
  # “publish_frequency”参数决定了代价地图发布可视化信息的频率。
  # 将“rolling_window”参数设置为true，意味着随着机器人在现实世界里移动，代价地图会保持以机器人为中心。
  # “width”、“height”、“resolution”参数分别设置局部代价地图的宽度(米)、高度(米)和分辨率(米/单元)。 
  # 注意，这里的分辨率和你的静态地图的分辨率可能不同，但我们通常把他们设成一样的。